#!/usr/bin/env bash

APP="summit360_www" # name of your release


BUILD_CMD="mix"
BUILD_HOST="helium.deploy" # host where to build the release
BUILD_USER="deploy" # local user at build host
BUILD_AT="~/tmp/builds/phoenix.summit360" # build directory on build host

# STAGING_HOSTS="test1.acme.org test2.acme.org" # staging / test hosts separated by space
# STAGING_USER="test" # local user at staging hosts
# TEST_AT="/test/my-erlang-app" # deploy directory on staging hosts. default is DELIVER_TO
RELEASE_CMD="mix"
PRODUCTION_HOSTS="helium.deploy" # deploy / production hosts separated by space
PRODUCTION_USER="deploy" # local user at deploy hosts
DELIVER_TO="~/apps/phoenix" # deploy directory on production hosts
